# Generated by Django 5.0.6 on 2024-07-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
