# Generated by Django 5.0.7 on 2024-07-22 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_question_answers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInTheBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_index', models.IntegerField()),
                ('correct_answer', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_in_the_blanks', to='core.question')),
            ],
        ),
    ]
