# Generated by Django 4.2.3 on 2024-07-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fillintheblank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('DD', 'Drag and Drop'), ('SIM', 'Simulation'), ('MAT', 'Matching'), ('FIB', 'Fill in the Blank')], db_index=True, max_length=3),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['test', 'question_type', 'order'], name='core_questi_test_id_aadca6_idx'),
        ),
    ]
