# Generated by Django 4.2.3 on 2024-07-26 15:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_question_order_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragdropitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_file_path),
        ),
    ]
