# Generated by Django 4.2.3 on 2024-07-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_dragdropitem_image_alter_question_image'),
        ('core', '0009_question_image_upload_status_and_more'),
    ]

    operations = [
    ]
