# Generated by Django 4.2.3 on 2024-08-03 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_dragdropitem_image_alter_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.CharField(choices=[('CORE1', 'Core 1'), ('CORE2', 'Core 2')], max_length=5)),
                ('domain', models.CharField(choices=[('MD', 'Mobile Devices'), ('NW', 'Networking'), ('HW', 'Hardware'), ('VC', 'Virtualization and Cloud Computing'), ('HNT', 'Hardware and Network Troubleshooting'), ('OS', 'Operating Systems'), ('SEC', 'Security'), ('ST', 'Software Troubleshooting'), ('OP', 'Operational Procedures')], max_length=3)),
            ],
            options={
                'unique_together': {('core', 'domain')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.category'),
        ),
    ]
