# Generated by Django 4.2.3 on 2024-08-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_simulation_goal_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='goal_state',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='initial_state',
        ),
    ]
