# Generated by Django 4.2.3 on 2024-08-13 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_question_explanation_questionresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='dragdropitem',
            name='correct_position',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fillintheblank',
            name='blank_index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='user_answer',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='answers',
            field=models.JSONField(help_text="JSON containing user's answers"),
        ),
        migrations.AlterField(
            model_name='result',
            name='category_scores',
            field=models.JSONField(default=dict, help_text='JSON containing category scores'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.PositiveIntegerField(help_text='Time limit in minutes'),
        ),
    ]
